version: '3.7'

services:
  prism:
    image: stoplight/prism:3
    ports:
      - 9080:9080
    volumes:
      - ../..:/todo-app
    command: mock -p 9080 -h 0.0.0.0 /todo-app/backend/rest-api-specification/openapi.yaml
