/* tslint:disable */
/* eslint-disable */
/**
 * ToDo REST API
 * サービス開発ハンズオンで作成するToDoアプリのREST API。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * CSRFトークン送信用ヘッダー名
     * @type {string}
     * @memberof InlineResponse200
     */
    csrfTokenHeaderName: string;
    /**
     * CSRFトークン値
     * @type {string}
     * @memberof InlineResponse200
     */
    csrfTokenValue: string;
}

export function InlineResponse200FromJSON(json: any): InlineResponse200 {
    return InlineResponse200FromJSONTyped(json, false);
}

export function InlineResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'csrfTokenHeaderName': json['csrfTokenHeaderName'],
        'csrfTokenValue': json['csrfTokenValue'],
    };
}

export function InlineResponse200ToJSON(value?: InlineResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'csrfTokenHeaderName': value.csrfTokenHeaderName,
        'csrfTokenValue': value.csrfTokenValue,
    };
}


